apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: solvox-gateway
  namespace: gateway-system
spec:
  gatewayClassName: gke-l7-global-external-managed
  addresses:
    - type: NamedAddress
      value: solvox-gateway-ip
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All