apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo
  namespace: gateway-system
spec:
  secretName: argo-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - argo.solvox.ai
